import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from store import *


PROMPT_TEMPLATE = '''
                  You are a careful Medical Assistant. Use the provided CONTEXT to answer the QUESTION.
                    - Be concise and clinically conscious.
                    - Include incline numeric citations like [1], [2] where you use evidence.
                    - End with a "References" section listing each cited item as [n] Source: PubMed ID.
                    - If you are unsure, say you are unsure and suggest consulting a clinician. 

                  QUESTION: {question}
                  CONTEXT:  {context}

                  ANSWER:
                  '''


class QAPipeline:
    def __init__(self, model_name: str):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForCausalLM.from_pretrained(model_name)

    def generate(self, prompt: str, max_new_tokens: int = 512, temperature: float = 0.1) -> str:
        prompt_tokens = self.tokenizer(prompt, return_tensors='pt').to(self.model.device)

        with torch.inference_mode():
            answer_tokens = self.model.generate(input_ids=prompt_tokens['input_ids'],
                                                attention_mask=prompt_tokens['attention_mask'],
                                                max_new_tokens=max_new_tokens,
                                                temperature=temperature,
                                                do_sample=temperature>0.0)

        answer = self.tokenizer.decode(answer_tokens[0], skip_special_tokens=True)
        return answer


if __name__ == "__main__":
    database = vector_database(model_name="sentence-transformers/all-MiniLM-L6-v2",
                               database_path="database/chroma")

    question = input("Enter your question: ")

    retrieve = database.search(query=question)                                  # generated by embedding model
    context = ""
    for index, reference in enumerate(retrieve, start=1):
        context += reference.format(index)

    prompt = PROMPT_TEMPLATE.format(question=question, context=context)

    pipeline = QAPipeline("mistralai/Mistral-7B-v0.1")
    answer = pipeline.generate(prompt)

    print("\n--- ANSWER ---")
    print(answer)                                                               # generated by text-generation model

    print("\n--- REFERENCES ---")
    for index, reference in enumerate(retrieve, start=1):
        print(f"[{index}] PubMed ID: {reference.meta.get('pubid', 'unknown')} | Section: {reference.meta.get('labels', 'unknown')} | Score: {reference.score:.4f}")                        
