import argparse
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from database import vector_database


device = "cuda:0" if torch.cuda.is_available() else "cpu"

PROMPT_TEMPLATE = ''' You are a careful Medical Assistant. Use the provided CONTEXT to answer the QUESTION.

 - Be concise and clinically conscious.
 - ONLY use the provided CONTEXT to answer. Do NOT use any outside knowledge.
 - Include inline numeric citations like [1], [2] where you use evidence. Do NOT generate a References or Bibliography section.
 - If the CONTEXT does not contain enough information, say so.
 - If you are unsure, say you are unsure and suggest consulting a clinician. 

QUESTION: {question}
CONTEXT:  {context}
'''


def instruct_format(model_name: str, prompt: str) -> str:
    if "mistral" in model_name.lower() and "instruct" in model_name.lower():
        # Mistral Instruct format
        return "<s>[INST]" + prompt + "[/INST]"
    elif "llama" in model_name.lower():
        # Llama Instruct form at
        return "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n" + prompt + "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n"
    elif "gemma" in model_name.lower():
        # Gemma Instruct format
        return "<start_of_turn>user\n" + prompt + "<end_of_turn>\n<start_of_turn>model\n"
    else: return prompt


class QAPipeline:
    def __init__(self, model_name: str):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForCausalLM.from_pretrained(model_name, dtype=torch.bfloat16).to(device)

    def generate(self, prompt: str, max_new_tokens: int = 512, temperature: float = 0.1) -> str:
        prompt_tokens = self.tokenizer(prompt, return_tensors='pt').to(self.model.device)
        prompt_len = len(prompt_tokens['input_ids'][0])

        with torch.inference_mode():
            answer_tokens = self.model.generate(input_ids=prompt_tokens['input_ids'],
                                                attention_mask=prompt_tokens['attention_mask'],
                                                max_new_tokens=max_new_tokens,
                                                temperature=temperature,
                                                do_sample=temperature>0.0)

        answer = self.tokenizer.decode(answer_tokens[0][prompt_len:], skip_special_tokens=True)                     # `model.generate() returns [query tokens + new tokens] for each batch`
                                                                                                                    # regardless of whether it is a base model/ instruction fine-tuned model
        return answer


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--question", type=str, required=True, help="Medical Query to be answered")
    parser.add_argument("--num_references", type=int, required=True, help="Number of references to cite")
    args = parser.parse_args()

    embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
    generator_model = "mistralai/Mistral-7B-Instruct-v0.2"

    database = vector_database(model_name=embedding_model,
                               database_path="database/chroma")
    retrieve = database.search(query=args.question, k=args.num_references)           # generated by embedding model

    context = ""
    for index, reference in enumerate(retrieve, start=1):
        context += reference.format(index)

    prompt = PROMPT_TEMPLATE.format(question=args.question, context=context)
    prompt = instruct_format(model_name=generator_model, prompt=prompt)

    pipeline = QAPipeline(generator_model)                                      # Use an instruction fine-tuned model instead of base model, because "new tokens" by
    answer = pipeline.generate(prompt)                                          # base model:                   contain query tokens + answer tokens
                                                                                # instruction fine-tuned model: contain only answer tokens

    print("\n--- ANSWER ---")
    print(answer)                                                               # generated by text-generation model

    print("\n--- REFERENCES ---")
    for index, reference in enumerate(retrieve, start=1):
        print(f"[{index}] PubMed ID: {reference.meta.get('pubid', 'unknown')} | Section: {reference.meta.get('labels', 'unknown')} | Score: {reference.score:.4f}")                        
